export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANTS_BY_ZIP = 'GET_RESTAURANTS_BY_ZIP';
export const GET_USER = 'GET_USER';

export const OWNER_ADDED = "OWNER_ADDED";
export const CUSTOMER_ADDED = "CUSTOMER_ADDED";
export const DRIVER_ADDED = "DRIVER_ADDED";
